{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2", "trace": "self = <test_mark_study.Test_Demo2 object at 0x0000020A18B90BC8>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.smoke\n    @pytest.mark.demo\n    def test_three(self):\n        b = 2\n>       assert 0 == b #注意：这个用例会失败\nE       assert 0 == 2\n\ntest_mark_study.py:20: AssertionError"}, "start": 1618644300735, "stop": 1618644300736, "uuid": "d0ae1d1d-58a0-42c3-9f38-0ad03c57b53e", "historyId": "d0603abf5d44504edca8f801f6750d23", "testCaseId": "24f8059f5ad4462629bbfcc3d3bbe9b9", "fullName": "test_mark_study.Test_Demo2#test_three", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_mark_study"}, {"name": "subSuite", "value": "Test_Demo2"}, {"name": "host", "value": "BY-20190922YINQ"}, {"name": "thread", "value": "14192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_study"}]}